# Generated by Django 4.1.2 on 2022-10-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_pagearticles_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='pagearticles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/', verbose_name='Изображение'),
        ),
    ]
