# Generated by Django 4.1.2 on 2022-11-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_category_image_alter_pagearticles_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagearticles',
            options={'ordering': ['-name'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterField(
            model_name='pagearticles',
            name='name',
            field=models.CharField(default=0, max_length=150, verbose_name='Название страницы'),
        ),
    ]
